### ISSUE TITLE
Accuracy does not run on activity "monitoring beacon"

### ISSUE THREAD

**Issue by ahmadtara02** [cubeacon/android-cubeacon-sample#19]
sorry for lot of question @alann-maulana

I tried to move "accuracy" to the activity "Monitoring beacon" but "accuracy" only saves and does not run like in activity "Ranging Beacon".
Can you help me ?

Best regards
![screenshot_20180521-152259](https://user-images.githubusercontent.com/39481050/40298150-46876af6-5d0c-11e8-8aca-90aed85d49c2.png)
![screenshot_20180521-152315](https://user-images.githubusercontent.com/39481050/40298151-46b4db4e-5d0c-11e8-8810-8d69d3531508.png)

**Comment by alann-maulana** [comment]
@ahmadtara02 Yes, you only get updated accuracy value from a ranging beacon function, not the monitoring one. Because monitoring beacon function are intended to check wether there is a beacon signal or not.
I'll close this issue now.
