### ISSUE TITLE
determine beacon

### ISSUE THREAD

**Issue by andra17** [cubeacon/android-cubeacon-sample#4]
i want to create two custom different campaign(campaign A & B) with two beacon in the same event(on Near) so went entering on near area of beacon B, it showing campaign campaign B and when entering on Near area A it showing campaign A, how can i do that?

Best Regards,

**Comment by alann-maulana** [comment]
Hi @andra17 ,

You can do this by logging into [Cubeacon Developer Page] -> `Your Apps` -> `Storyline Menu`. Then, create your multiple campaign using multiple beacons here. For example, I have setup some storyline like this [screenshoot].

Best Regards.

[Cubeacon Developer Page]: https://developer.cubeacon.com
[screenshoot]: https://drive.google.com/file/d/0BxchwEga3C3AXzZOdVV0X2VtUlU/preview?pli=1

**Comment by andra17** [comment]
thats for the default campaign that available on the cubeacon developer page, i mean ,if i want to create my default campaign such as opening login page,so beacon A open a login page and beacon B do something else , what should i do?

Best Regards.

**Comment by alann-maulana** [comment]
Hi @andra17 

Just like issue #3 you can provide a storyline with `Near` event, disable all campaign days and then add your custom code to the callback function of `onNearBeacon`

```java
    @Override
    protected void onNearBeacon(CBBeacon beacon) {
        // TODO: when the beacon proximity are near
        // for example showing login activity when beacon with UUID: a, Major: b, Minor: c
		if (beacon.getProximityUUID().equals(a)
			&& beacon.getMajor() == b
			&& beacon.getMinor() == c) {
			Intent intent = new Intent(this, LoginActivity.class);
			startActivity(intent);
		} else {
			// do something else
		}
    }
```

For a complete references about SDK API Documentation, you can visit this [page]

[page]: http://docs.cubeacon.com/sdk/android/references/index.html

**Comment by andra17** [comment]
ooh okey got it thank you very much, so helpful for beginner :)

best regards,

**Comment by alann-maulana** [comment]
OK @andra17 you're welcome.
