### ISSUE TITLE
protected void

### ISSUE THREAD

**Issue by andra17** [cubeacon/android-cubeacon-sample#6]
I want to make my custom activity when my device enter beacon area,here is my code :

protected void onEnteredBeacon(CBBeacon beacon){
Intent i=new intent(mainactivity.this,register.class);
startActivity (i);
super.onEnteredBeacon(beacon);}

But when i run it on my device the register activity couldnt show up, why is this happening and how to solve it? 
Regards

**Comment by alann-maulana** [comment]
Hi @andra17 

First, check if your storyline are enabled on **Cubeacon Developer**. If you want to disabled the default storyline campaign, you can uncheck all the schedule days from storyline. So it will just call the callback event on the SDK. 

Regards.

**Comment by andra17** [comment]
Already done,but still not working
It works perfectly when i only call layout

protected void onEnteredBeacon(CBBeacon beacon){ 
setContentView(R.layout.activity);} 

But when im trying to call other class (explained bfore) its not working...any other idea? :)

Regards

**Comment by alann-maulana** [comment]
Hi @andra17 

We are already trying to reproduce your code into our **Android Cubeacon Sample**. You can `pull` to update from this repository. Here is some code we reproduce :
 - [MainActivity class]
```java
    @Override
    protected void onEnteredBeacon(CBBeacon beacon) {
        // TODO Auto-generated method stub
		String message = beacon.getName() + " entered, major: " + beacon.getMajor() + ", minor: " + beacon.getMinor();
        Log.i(tag, message);
		Intent intent = new Intent(this, BeaconActivity.class);
		intent.putExtra(MainActivity.EXTRA_INTENT, message);
		startActivity(intent);
    }
```
 - [BeaconActivity class]
```java
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_beacon);
        getActionBar().setDisplayHomeAsUpEnabled(true);
        
        Bundle bundle = getIntent().getExtras();
        String message = bundle.getString(MainActivity.EXTRA_INTENT);
		Toast.makeText(this, message, Toast.LENGTH_LONG).show();
        
        // .......
    }
```
It's running well. You can try it.

Regards.
[MainActivity class]: https://github.com/cubeacon/android-cubeacon-sample/blob/master/src/com/eyro/cubeacon/demos/MainActivity.java
[BeaconActivity class]: https://github.com/cubeacon/android-cubeacon-sample/blob/master/src/com/eyro/cubeacon/demos/BeaconActivity.java

**Comment by andra17** [comment]
working perfectly :) thanks a lot

**Comment by alann-maulana** [comment]
You're welcome @andra17 . If you need another questions, please open a new issue.

Thanks and regards.

**Comment by andra17** [comment]
and how to send my beacon id information to my server? (im using my sql)
