### ISSUE TITLE
beacon id

### ISSUE THREAD

**Issue by andra17** [cubeacon/android-cubeacon-sample#7]
sorry for lot of question @alann-maulana 

Can i  send my beacon id(uuid, major,minor) and store it my sql server? 

Best regards

**Comment by alann-maulana** [comment]
@andra17 

Yes, you can. You can get UUID, major and minor value when detected beacon using this [reference]. Then you can send and store it on your own database. There is plenty of third party library outside there or you can create on your own library about how to store data from Android to another database.

Regards.

[reference]: http://docs.cubeacon.com/sdk/android/references/index.html

**Comment by andra17** [comment]
So i can get it when using cbbeacon?

**Comment by alann-maulana** [comment]
Yes @andra17 

Regards.
